name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        args: --build-tags=e2e --skip-dirs 'mock*'

    - name: Test
      run: ./script/test all
      env:
        BYBIT_HOST: ${{ secrets.TEST_BYBIT_HOST }}
        BYBIT_KEY: ${{ secrets.TEST_BYBIT_KEY }}
        BYBIT_SEC: ${{ secrets.TEST_BYBIT_SEC }}
